export const COMPANY_INDUSTRIES = [
  "Technology / IT",
  "Software and ITES",
  "Fintech",
  "Banking",
  "Insurance",
  "Telecommunications",
  "E-commerce",
  "Retail",
  "FMCG",
  "Food and Beverage",
  "Textile and Apparel",
  "Manufacturing",
  "Automotive",
  "Pharmaceuticals",
  "Healthcare and Hospitals",
  "Education",
  "Media and Entertainment",
  "Marketing and Advertising",
  "Consulting",
  "Real Estate",
  "Construction",
  "Logistics and Courier",
  "Hospitality and Tourism",
  "Agriculture",
  "Government and Public Sector",
  "Nonprofit / Development",
  "Other",
] as const
