export const PAKISTANI_UNIVERSITIES = [
  "Aga Khan University",
  "Air University",
  "Allama Iqbal Open University",
  "Bahauddin Zakariya University",
  "Bahria University",
  "Beaconhouse National University",
  "COMSATS University Islamabad",
  "Dow University of Health Sciences",
  "FAST-NUCES",
  "Fatima Jinnah Women University",
  "Forman Christian College (FCCU)",
  "Ghulam Ishaq Khan Institute (GIKI)",
  "Government College University Faisalabad",
  "Government College University Lahore",
  "Habib University",
  "Hamdard University",
  "IBA Karachi",
  "IBA Sukkur",
  "Information Technology University (ITU)",
  "Institute of Business Management (IoBM)",
  "Institute of Management Sciences (IMSciences)",
  "International Islamic University Islamabad",
  "Islamia University of Bahawalpur",
  "King Edward Medical University",
  "Lahore College for Women University",
  "Lahore School of Economics",
  "Lahore University of Management Sciences (LUMS)",
  "Mehran University of Engineering and Technology",
  "National College of Arts",
  "National University of Modern Languages (NUML)",
  "National University of Sciences and Technology (NUST)",
  "NED University of Engineering and Technology",
  "Pakistan Institute of Engineering and Applied Sciences (PIEAS)",
  "Pir Mehr Ali Shah Arid Agriculture University",
  "Quaid-i-Azam University",
  "Riphah International University",
  "Shaheed Zulfikar Ali Bhutto Institute of Science and Technology (SZABIST)",
  "The Islamia University of Bahawalpur",
  "University of Agriculture Faisalabad",
  "University of Central Punjab",
  "University of Engineering and Technology Lahore",
  "University of Engineering and Technology Peshawar",
  "University of Engineering and Technology Taxila",
  "University of Gujrat",
  "University of Health Sciences Lahore",
  "University of Karachi",
  "University of Lahore",
  "University of Management and Technology (UMT)",
  "University of Peshawar",
  "University of Punjab",
  "University of Sargodha",
  "University of Sindh",
  "University of the Punjab",
  "University of Veterinary and Animal Sciences",
] as const

export const UNIVERSITY_OTHER = "Other (type your own)"
